version: '3'

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_DB: tour_planner_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
